### PR TITLE
Issue #63: Use aws_signature for signing of requests rather than aws-erlang's own implementation

### LINKED ISSUE #63: Any reason for aws-erlang to not use aws_signature?
Hi there,

TLDR:
Is there any reason why `aws-erlang` does not use [aws_signature](https://github.com/aws-beam/aws_signature)? 

At my company we use `aws-erlang` extensively to interact with S3 and we've had several issues with `aws-erlang` over the past month or so leading us to consider `erlcloud` which is a shame :disappointed: 

The problems seem to stem from `aws-erlang` implementing it's own version of `aws_signature` natively inside [aws_request:sign_request/5](https://github.com/aws-beam/aws-erlang/blob/master/src/aws_request.erl#L25) rather than use `aws_signature`. 

List of issues that have been discovered with signatures:
https://github.com/aws-beam/aws-erlang/pull/61
https://github.com/aws-beam/aws-erlang/pull/62

Both of the above issues are fixed in `aws_signature` which is also the library of choice for [aws-elixir](https://github.com/aws-beam/aws-elixir) as can be seen here: [mix.exs#L30](https://github.com/aws-beam/aws-elixir/blob/master/mix.exs#L30). 

In general it seems that there are a few diffs between `aws-elixir` and `aws-erlang` where fixes in one, are not ported to the other or even at the very least opened up as an issue for someone to grab. The further this goes, the more problematic it will be to figure out the diff and apply those to get back in line with eachother. I for one am not even sure if the fixes that we (from Klarna) have implemented on `aws-erlang` are ported to `aws-elixir` for example and if they're even applicable there since we don't use Elixir and have no good way of testing this either. 

If there's no good reason for `aws-erlang` having it's own implementation, I'd like to really comb the code of `aws_signature` and see if there are any differences that could lead to a regression and if it's feasible to simply replace [aws_request:sign_request/5](https://github.com/aws-beam/aws-erlang/blob/master/src/aws_request.erl#L25) with a call to [aws_signature:sign_v4/10](https://github.com/aws-beam/aws_signature/blob/main/src/aws_signature.erl#L66) with the respective option dance of `uri_encode_path` for S3 as that's apparently special :-)

### PR DESCRIPTION
**Pull request by onno-vos-dev**
Fixes #63 

Historically `aws-erlang` has struggled a bit when it came to signature signing resulting in the dreaded `SignatureDoesNotMatch` errors which are a massive pain to debug. This meant certain bits of `aws_signature` had to be backported into `aws-erlang`'s implementation which is very error prone. Removing all logic for signature signing from `aws-erlang` and making use of `aws_signature` instead closes that long standing issue and ensures that signature signing is unified among `aws-elixir` and `aws-erlang` :tada: :clinking_glasses: 

I understand that the diff is a mess but that's kinda unavoidable... I'll point out a few areas of interest where I'd like some additional eyes in particular.

I haven't decided whether or not I want to keep `aws_request` around or move the signing part into `aws-codegen`. I believe "most" already sits in `aws-codegen` so I'll take a look when it's time to address https://github.com/aws-beam/aws-erlang/pull/125#discussion_r1104130434 and https://github.com/aws-beam/aws-erlang/pull/125#discussion_r1104140261 (on my todo list)

### CODE REVIEW

File: src/aws_request.erl [hunk 1]
```diff
@@ -31,14 +22,17 @@ request(RequestFun, Options) ->
...
     AccessKeyID = maps:get(access_key_id, Client),
     SecretAccessKey = maps:get(secret_access_key, Client),
     Region = maps:get(region, Client),
     Service = maps:get(service, Client),
     Token = maps:get(token, Client, undefined),
-    sign_request(AccessKeyID, SecretAccessKey, Region, Service, Token,
-                 Method, URL, Headers, Body).
+    Headers = case Token of
+                undefined -> Headers0;
+                _ -> [{<<"X-Amz-Security-Token">>, hackney_url:urlencode(Token)}|Headers0]
```
Comment (onno-vos-dev) [inline src/aws_request.erl:33]: Not a huge fan of `hackney_url:urlencode/1` here and to be 100% honest I'm not sure it's even needed but since my Client doesn't include a token for regular requests, I cannot test this. I've therefor kept it the same as in `aws_s3_presigned_url`. So see comment on that module.

File: src/aws_s3_presigned_url.erl [hunk 2]
```diff
@@ -23,23 +23,22 @@ make_presigned_v4_url(Client0, Method, ExpireSeconds, Bucket, Key) ->
...
-    ShortDate = list_to_binary(ec_date:format("Ymd", Now)),
-    Credential = make_credential(AccessKeyID, ShortDate, Region),
-    Headers0 = [{<<"Host">>, Host},
-                {<<"X-Amz-Algorithm">>, <<"AWS4-HMAC-SHA256">>},
-                {<<"X-Amz-Credential">>, Credential},
-                {<<"X-Amz-Date">>, list_to_binary(ec_date:format("YmdTHisZ", Now))},
-                {<<"X-Amz-Expires">>, integer_to_binary(ExpireSeconds)},
-                {<<"X-Amz-SignedHeaders">>, <<"host">>}
+    Options0 = [ {ttl, ExpireSeconds}
+               , {body_digest, <<"UNSIGNED-PAYLOAD">>}
```
Comment (onno-vos-dev) [inline src/aws_s3_presigned_url.erl:33]: Since the old implementation was sending in `UNSIGNED-PAYLOAD` as the payload (See the !Important box at [sig-v4-header-based-auth](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) I've kept this. I'm not sure if clients may already use presigned urls but figured I'd keep the same signature of the URL in place.

File: src/aws_s3_presigned_url.erl [hunk 3]
```diff
@@ -23,23 +23,22 @@ make_presigned_v4_url(Client0, Method, ExpireSeconds, Bucket, Key) ->
...
                ],
-    Headers = maybe_add_security_token(Headers0, SecurityToken),
-    Signature = sign_request(Client, MethodBin, BaseHost, aws_request:add_query(URL0, Headers), [{<<"Host">>, BaseHost}], Now, <<"UNSIGNED-PAYLOAD">>),
-    FinalHeaders = lists:keysort(1, [{<<"X-Amz-Signature">>, Signature} | Headers]),
-    {ok, aws_request:add_query(URL0, FinalHeaders)}.
+    Options = case SecurityToken of
+                undefined ->
+                  Options0;
+                _ ->
+                  [{session_token, hackney_url:urlencode(SecurityToken)} | Options0]
```
Comment (onno-vos-dev) [inline src/aws_s3_presigned_url.erl:39]: The issue here seems to be that the CanonicalRequest that `aws_signature` builds up does not urlencode the `session_token` while AWS itself does when it calculates it's own CanonicalRequest in order to compare signatures. Rather than making the change in `aws_signature` and potentially breaking `aws-elixir` I've moved the change in here. 

@philss Since you're closest to `aws-elixir` to my knowledge, are you aware of any issues regarding this? Nor do you seem to urlencode the token prior to setting the header (See: [signature.ex#L16](https://github.com/aws-beam/aws-elixir/blob/cadf6502f238990f95e0e51190ecb08ce5e4a0a8/lib/aws/signature.ex#L16)) which confuses me a bit. Perhaps this is only necessary for presigned urls and hence [my other comment](https://github.com/aws-beam/aws-erlang/pull/126/files#r1107781493) should be reverted out?

Comment (jadeallenx) [reply src/aws_s3_presigned_url.erl:39]: Shouldn't we try to use https://github.com/aws-beam/aws_signature/blob/main/src/aws_signature.erl#L101 here?

Comment (philss) [reply src/aws_s3_presigned_url.erl:39]: @onno-vos-dev I'm not sure, but I think it may be because this is more relevant for the URLs.

I think @jadeallenx 's suggestion makes sense! That function accepts a `session_token` as option, but it does not encode it, for what I could see. Maybe we didn't test that part.

**Review by philss — COMMENTED** [review]
Awesome! :smiley:  :tada:

File: src/aws_s3_presigned_url.erl (hunk 3 above)
Comment (onno-vos-dev) [reply src/aws_s3_presigned_url.erl:39]: > Shouldn't we try to use https://github.com/aws-beam/aws_signature/blob/main/src/aws_signature.erl#L101 here?

That is the one I'm using? :-) I'm passing in `options` with the `session_token` but apparently it requires urlencoding to pass. And that feels kinda odd to me but since I don't have an Elixir example at hand I'm not sure if this is "correct" or not :-) It seems to be.

File: rebar.config [hunk 4]
```diff
@@ -1,7 +1,8 @@
 {erl_opts, [debug_info, {d, maps_support}]}.
 {deps, [{erlware_commons, "1.6.0"},
         {hackney, "1.18.0"},
-        {jsx, "3.0.0"}
+        {jsx, "3.0.0"},
+        {aws_signature, "0.3.1"}
```
Comment (andreashasse) [inline rebar.config:5]: Reflect this in the .app.src file.

File: src/aws_request.erl [hunk 5]
```diff
@@ -305,210 +168,3 @@ should_retry(#{ type := exponential_with_jitter
   Sleep = Temp div 2 + rand:uniform(Temp div 2),
   timer:sleep(Sleep),
   {ok, RetryState0#{ n => N +1 }}.
-
-%%====================================================================
-%% Unit tests
-%%====================================================================
-
--ifdef(TEST).
```
Comment (andreashasse) [inline src/aws_request.erl:313]: How is the test quality in aws_signature? Can we move some of these tests over?

Comment (onno-vos-dev) [reply src/aws_request.erl:313]: I will double check but just a quick browse shows that most if not all tests that I removed here are covered in `aws_signature`.
Cover coverage report for `aws_signature`:
```
  |------------------------|------------|
  |                module  |  coverage  |
  |------------------------|------------|
  |         aws_signature  |       99%  |
  |   aws_signature_utils  |       90%  |
  |------------------------|------------|
  |                 total  |       97%  |
  |------------------------|------------|
  ```

**Review by andreashasse — APPROVED** [review]

File: src/aws_s3_presigned_url.erl (hunk 3 above)
Comment (jadeallenx) [reply src/aws_s3_presigned_url.erl:39]: OK, sorry - I missed that you were already calling that function
